# Generated by Django 5.1.1 on 2024-11-07 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='embalagem',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
