# Generated by Django 5.1.1 on 2024-10-05 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='sku',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Atributo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Producao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('horainicial', models.TimeField(auto_now_add=True)),
                ('horafinal', models.TimeField(auto_now_add=True)),
                ('quantidade', models.IntegerField()),
                ('perda', models.FloatField()),
                ('motivoperda', models.CharField(max_length=100)),
                ('ciclo', models.FloatField()),
                ('lote', models.CharField(max_length=100)),
                ('observacao', models.TextField()),
                ('status', models.BooleanField(default=True)),
                ('atributo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.atributo')),
                ('embalador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embalador', to='cadastros.colaborador')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.empresa')),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.maquina')),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operador', to='cadastros.colaborador')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.produto')),
            ],
        ),
    ]
