# Generated by Django 5.1.1 on 2024-10-23 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producao',
            name='ciclo',
            field=models.FloatField(null=True),
        ),
    ]
