# Generated by Django 5.1.1 on 2024-10-23 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_alter_producao_ciclo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producao',
            name='perda',
            field=models.FloatField(null=True),
        ),
    ]
