# Generated by Django 5.1.1 on 2024-10-04 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_remove_perfil_id_remove_usuarioempresa_id_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usuarioempresa',
            unique_together=set(),
        ),
    ]
