# Generated by Django 5.1.1 on 2024-11-11 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0003_insumo'),
    ]

    operations = [
        migrations.AddField(
            model_name='log_cadastro',
            name='insumo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cadastros.insumo'),
        ),
    ]
