# Generated by Django 5.1.1 on 2024-10-23 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0004_alter_producao_motivoperda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producao',
            name='horafinal',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='producao',
            name='horainicial',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='producao',
            name='lote',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='producao',
            name='observacao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
