# Generated by Django 5.1.1 on 2024-10-24 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0005_alter_producao_horafinal_alter_producao_horainicial_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log_cadastro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comando', models.CharField(max_length=100)),
                ('datagravacao', models.DateTimeField()),
                ('usuariogravacao', models.CharField(max_length=100)),
                ('atributo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cadastros.atributo')),
                ('colaborador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cadastros.colaborador')),
                ('empresa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cadastros.empresa')),
                ('maquina', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cadastros.maquina')),
                ('molde', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cadastros.molde')),
                ('producao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cadastros.producao')),
                ('produto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cadastros.produto')),
            ],
        ),
    ]
