# Generated by Django 5.1.1 on 2024-11-18 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0005_insumo_codigowms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumo',
            name='classe',
            field=models.CharField(max_length=100),
        ),
    ]
