# Generated by Django 5.1.1 on 2024-12-02 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0006_alter_insumo_classe'),
    ]

    operations = [
        migrations.AddField(
            model_name='producao',
            name='trocacor',
            field=models.FloatField(null=True),
        ),
    ]
