# Generated by Django 5.1.1 on 2024-12-04 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0007_producao_trocacor'),
    ]

    operations = [
        migrations.AddField(
            model_name='producao',
            name='atributo_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
