# Generated by Django 5.1.1 on 2024-11-11 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros', '0004_log_cadastro_insumo'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAlmoxarifado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=10)),
                ('datagravacao', models.DateTimeField()),
                ('usuariogravacao', models.CharField(max_length=100)),
                ('tipo_movimentacao', models.CharField(choices=[('RETIRADA', 'RETIRADA'), ('DEVOLUÇÃO', 'DEVOLUÇÃO')], max_length=100)),
                ('statuswms', models.BooleanField(default=False)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.empresa')),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.insumo')),
            ],
        ),
    ]
