# Generated by Django 5.1.1 on 2024-11-08 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaquinaPcp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PARADA', 'PARADA'), ('EM PRODUÇÃO', 'EM PRODUÇÃO'), ('TROCA DE MOLDE', 'TROCA DE MOLDE')], max_length=100)),
                ('prioridade', models.BooleanField(default=False)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.empresa')),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.maquina')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.produto')),
            ],
        ),
        migrations.CreateModel(
            name='ProducaoPcp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arte', models.CharField(blank=True, max_length=100, null=True)),
                ('quantidade', models.IntegerField()),
                ('ordem', models.IntegerField()),
                ('status', models.CharField(choices=[('FILA P/ PRODUZIR', 'FILA P/ PRODUZIR'), ('EM PRODUÇÃO', 'EM PRODUÇÃO'), ('FINALIZADA', 'FINALIZADA'), ('NÃO FINALIZADA', 'NÃO FINALIZADA')], max_length=100)),
                ('horainicial', models.DateTimeField(blank=True, null=True)),
                ('horafinal', models.DateTimeField(blank=True, null=True)),
                ('qnt_produzida', models.IntegerField(blank=True, null=True)),
                ('atributo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.atributo')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.empresa')),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pcp.maquinapcp')),
            ],
        ),
        migrations.CreateModel(
            name='InsumosPcp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caixas', models.IntegerField()),
                ('pigmento', models.DecimalField(decimal_places=3, max_digits=10)),
                ('qnt_material', models.DecimalField(decimal_places=3, max_digits=10)),
                ('embalagem', models.IntegerField()),
                ('producao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pcp.producaopcp')),
            ],
        ),
        migrations.CreateModel(
            name='SoldaPcp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('ordem', models.IntegerField()),
                ('status', models.CharField(choices=[('FILA P/ PRODUZIR', 'FILA P/ PRODUZIR'), ('EM PRODUÇÃO', 'EM PRODUÇÃO'), ('FINALIZADA', 'FINALIZADA'), ('NÃO FINALIZADA', 'NÃO FINALIZADA')], max_length=100)),
                ('horainicial', models.DateTimeField(blank=True, null=True)),
                ('horafinal', models.DateTimeField(blank=True, null=True)),
                ('qnt_produzida', models.IntegerField(blank=True, null=True)),
                ('cor_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.atributo')),
                ('cor_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.atributo')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.empresa')),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pcp.maquinapcp')),
            ],
        ),
    ]
