# Generated by Django 5.1.1 on 2024-11-08 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
        ('pcp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soldapcp',
            name='cor_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soldapcp_cor1', to='cadastros.atributo'),
        ),
        migrations.AlterField(
            model_name='soldapcp',
            name='cor_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soldapcp_cor2', to='cadastros.atributo'),
        ),
    ]
