# Generated by Django 5.1.1 on 2024-11-11 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcp', '0003_rename_quantidade_producaopcp_unidades_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maquinapcp',
            name='status',
            field=models.CharField(choices=[('PARADA', 'PARADA'), ('EM PRODUÇÃO', 'EM PRODUÇÃO'), ('TROCA DE MOLDE', 'TROCA DE MOLDE'), ('FILA DE PRODUÇÃO', 'FILA DE PRODUÇÃO')], max_length=100),
        ),
    ]
