# Generated by Django 5.1.1 on 2024-10-30 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcp', '0003_producaopcp_horafinal_producaopcp_horainicial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producaopcp',
            name='horafinal',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
