# Generated by Django 5.1.1 on 2024-11-12 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0005_insumo_codigowms'),
        ('pcp', '0004_alter_maquinapcp_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmbaladoresPcp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setor', models.CharField(choices=[('INJETORA', 'INJETORA'), ('SOLDA', 'SOLDA'), ('CANUDOS', 'CANUDOS')], max_length=100)),
                ('embalador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.colaborador')),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pcp.maquinapcp')),
            ],
        ),
    ]
