# Generated by Django 5.1.1 on 2024-10-31 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcp', '0004_alter_producaopcp_horafinal'),
    ]

    operations = [
        migrations.AddField(
            model_name='producaopcp',
            name='pigmento',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producaopcp',
            name='qnt_produzida',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
