# Generated by Django 5.1.1 on 2024-11-12 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0005_insumo_codigowms'),
        ('pcp', '0005_embaladorespcp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='embaladorespcp',
            name='embalador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cadastros.colaborador'),
        ),
        migrations.AlterField(
            model_name='embaladorespcp',
            name='setor',
            field=models.CharField(blank=True, choices=[('INJETORA', 'INJETORA'), ('SOLDA', 'SOLDA'), ('CANUDOS', 'CANUDOS')], max_length=100, null=True),
        ),
    ]
