# Generated by Django 5.1.1 on 2024-10-31 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcp', '0005_producaopcp_pigmento_producaopcp_qnt_produzida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producaopcp',
            name='pigmento',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
