# Generated by Django 5.1.1 on 2024-11-04 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcp', '0006_alter_producaopcp_pigmento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producaopcp',
            name='caixas',
        ),
        migrations.RemoveField(
            model_name='producaopcp',
            name='pigmento',
        ),
        migrations.CreateModel(
            name='InsumosPcp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caixas', models.IntegerField()),
                ('pigmento', models.DecimalField(decimal_places=3, max_digits=10)),
                ('qnt_material', models.DecimalField(decimal_places=3, max_digits=10)),
                ('embalagem', models.IntegerField()),
                ('producao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pcp.producaopcp')),
            ],
        ),
    ]
