# Generated by Django 5.1.1 on 2024-11-07 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcp', '0007_remove_producaopcp_caixas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maquinapcp',
            name='prioridade',
            field=models.BooleanField(default=False),
        ),
    ]
