# Generated by Django 5.1.1 on 2024-11-14 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcp', '0007_alter_embaladorespcp_setor_canudopcp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='canudopcp',
            old_name='quantidade',
            new_name='unidades',
        ),
        migrations.AddField(
            model_name='canudopcp',
            name='kilogramas',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='canudopcp',
            name='tamanho',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
