# Generated by Django 5.1.1 on 2024-11-18 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcp', '0008_rename_quantidade_canudopcp_unidades_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producaopcp',
            name='falta',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='producaopcp',
            name='pedido',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='producaopcp',
            name='saida',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='producaopcp',
            name='kilogramas',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
    ]
