# Generated by Django 5.1.1 on 2024-11-07 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pcp', '0008_maquinapcp_prioridade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maquinapcp',
            old_name='prioridade',
            new_name='prioriedade',
        ),
    ]
