# Generated by Django 5.1.1 on 2024-11-07 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pcp', '0009_rename_prioridade_maquinapcp_prioriedade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maquinapcp',
            old_name='prioriedade',
            new_name='prioridade',
        ),
    ]
