# Generated by Django 5.1.1 on 2024-11-07 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcp', '0010_rename_prioriedade_maquinapcp_prioridade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producaopcp',
            name='status',
            field=models.CharField(choices=[('FILA P/ PRODUZIR', 'FILA P/ PRODUZIR'), ('EM PRODUÇÃO', 'EM PRODUÇÃO'), ('FINALIZADA', 'FINALIZADA'), ('NÃO FINALIZADA', 'NÃO FINALIZADA')], max_length=100),
        ),
    ]
