# Generated by Django 5.1.1 on 2024-11-21 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0006_alter_insumo_classe'),
        ('pcp', '0010_alter_producaopcp_saida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producaopcp',
            name='falta',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='TrocaMoldePcp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_molde', models.CharField(choices=[('NÃO INICIADA', 'NÃO INICIADA'), ('EM EXECUÇÃO', 'EM EXECUÇÃO'), ('CONCLUÍDA', 'CONCLUÍDA')], max_length=50)),
                ('status_troca', models.CharField(choices=[('PARADA', 'PARADA'), ('EM PRODUÇÃO', 'EM PRODUÇÃO'), ('FILA DE PRODUÇÃO', 'FILA DE PRODUÇÃO')], max_length=50)),
                ('data_prevista', models.DateTimeField(blank=True, null=True)),
                ('data_realizada', models.DateTimeField(blank=True, null=True)),
                ('observacoes', models.CharField(blank=True, max_length=100, null=True)),
                ('injetora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.maquina')),
                ('molde_maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.molde')),
                ('proximo_molde', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.molde')),
            ],
        ),
    ]
