# Generated by Django 5.1.1 on 2024-11-21 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcp', '0011_alter_producaopcp_falta_trocamoldepcp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trocamoldepcp',
            name='status_troca',
            field=models.CharField(choices=[('PRODUZIDO', 'PRODUZIDO'), ('EM PRODUÇÃO', 'EM PRODUÇÃO'), ('FILA DE PRODUÇÃO', 'FILA DE PRODUÇÃO')], max_length=50),
        ),
    ]
