# Generated by Django 5.1.1 on 2024-11-07 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_produto_embalagem'),
        ('pcp', '0011_alter_producaopcp_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoldaPcp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('ordem', models.IntegerField()),
                ('status', models.CharField(choices=[('FILA P/ PRODUZIR', 'FILA P/ PRODUZIR'), ('EM PRODUÇÃO', 'EM PRODUÇÃO'), ('FINALIZADA', 'FINALIZADA'), ('NÃO FINALIZADA', 'NÃO FINALIZADA')], max_length=100)),
                ('horainicial', models.DateTimeField(blank=True, null=True)),
                ('horafinal', models.DateTimeField(blank=True, null=True)),
                ('qnt_produzida', models.IntegerField(blank=True, null=True)),
                ('cor_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.atributo')),
                ('cor_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.atributo')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.empresa')),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pcp.maquinapcp')),
            ],
        ),
    ]
