# Generated by Django 5.1.1 on 2024-11-08 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcp', '0012_soldapcp'),
    ]

    operations = [
        migrations.AddField(
            model_name='producaopcp',
            name='arte',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
