# Generated by Django 5.1.1 on 2024-11-22 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0006_alter_insumo_classe'),
        ('pcp', '0012_alter_trocamoldepcp_status_troca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trocamoldepcp',
            name='molde_maquina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pcp.TrocaMoldePcp.molde_maquina', to='cadastros.molde'),
        ),
        migrations.AlterField(
            model_name='trocamoldepcp',
            name='proximo_molde',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pcp.TrocaMoldePcp.proximo_molde', to='cadastros.molde'),
        ),
        migrations.AlterField(
            model_name='trocamoldepcp',
            name='status_molde',
            field=models.CharField(choices=[('PRODUZIDO', 'PRODUZIDO'), ('EM PRODUÇÃO', 'EM PRODUÇÃO'), ('FILA DE PRODUÇÃO', 'FILA DE PRODUÇÃO')], max_length=50),
        ),
        migrations.AlterField(
            model_name='trocamoldepcp',
            name='status_troca',
            field=models.CharField(choices=[('NÃO INICIADA', 'NÃO INICIADA'), ('EM EXECUÇÃO', 'EM EXECUÇÃO'), ('CONCLUÍDA', 'CONCLUÍDA')], max_length=50),
        ),
    ]
