# Generated by Django 5.1.1 on 2025-06-10 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0008_producao_atributo_2'),
        ('pcp', '0014_trocamoldepcp_ordem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maquinapcp',
            name='id',
        ),
        migrations.AlterField(
            model_name='maquinapcp',
            name='maquina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='cadastros.maquina'),
        ),
    ]
